var hierarchy =
[
    [ "acceleration_t", "structacceleration__t.html", null ],
    [ "ACCELERO_DrvTypeDef", "structACCELERO__DrvTypeDef.html", null ],
    [ "ACCELERO_FilterConfigTypeDef", "structACCELERO__FilterConfigTypeDef.html", null ],
    [ "ACCELERO_InitTypeDef", "structACCELERO__InitTypeDef.html", null ],
    [ "adv7533ConfigTypeDef", "structadv7533ConfigTypeDef.html", null ],
    [ "AUDIO_DrvTypeDef", "structAUDIO__DrvTypeDef.html", null ],
    [ "AUDIOIN_TypeDef", "structAUDIOIN__TypeDef.html", null ],
    [ "CAMERA_DrvTypeDef", "structCAMERA__DrvTypeDef.html", null ],
    [ "ChartData", "structChartData.html", null ],
    [ "CombineLatest< Ts >", "classCombineLatest.html", null ],
    [ "CombineLatest< DataQueue< velocity_t >, DataQueue< voltage_t > >", "classCombineLatest.html", null ],
    [ "ctrl_error_status_t", "unionctrl__error__status__t.html", null ],
    [ "ctrl_rx_status_t", "unionctrl__rx__status__t.html", null ],
    [ "ctrl_status_t", "unionctrl__status__t.html", null ],
    [ "DataAggregator", "classDataAggregator.html", null ],
    [ "DataAggregatorWrapper", "structDataAggregatorWrapper.html", null ],
    [ "EPD_DrvTypeDef", "structEPD__DrvTypeDef.html", null ],
    [ "ft5336_handle_TypeDef", "structft5336__handle__TypeDef.html", null ],
    [ "ft6x06_handle_TypeDef", "structft6x06__handle__TypeDef.html", null ],
    [ "gps_coordinate_t", "structgps__coordinate__t.html", null ],
    [ "GYRO_DrvTypeDef", "structGYRO__DrvTypeDef.html", null ],
    [ "GYRO_FilterConfigTypeDef", "structGYRO__FilterConfigTypeDef.html", null ],
    [ "GYRO_InitTypeDef", "structGYRO__InitTypeDef.html", null ],
    [ "GYRO_InterruptConfigTypeDef", "structGYRO__InterruptConfigTypeDef.html", null ],
    [ "iCommsMessage_t", "structiCommsMessage__t.html", null ],
    [ "ICommsMessageInfo", "structICommsMessageInfo.html", null ],
    [ "id_reg_t", "structid__reg__t.html", null ],
    [ "IDD_ConfigTypeDef", "structIDD__ConfigTypeDef.html", null ],
    [ "IDD_dbgTypeDef", "structIDD__dbgTypeDef.html", null ],
    [ "IDD_DrvTypeDef", "structIDD__DrvTypeDef.html", null ],
    [ "Identifiable", "classIdentifiable.html", [
      [ "CANLogEntry", "classCANLogEntry.html", null ],
      [ "ObserverToken", "classObserverToken.html", null ]
    ] ],
    [ "IO_DrvTypeDef", "structIO__DrvTypeDef.html", null ],
    [ "LCD_DrvTypeDef", "structLCD__DrvTypeDef.html", null ],
    [ "MAGNETO_DrvTypeDef", "structMAGNETO__DrvTypeDef.html", null ],
    [ "MAGNETO_InitTypeDef", "structMAGNETO__InitTypeDef.html", null ],
    [ "Observable< T >", "classObservable.html", null ],
    [ "pressure_t", "structpressure__t.html", null ],
    [ "QSPI_Info", "structQSPI__Info.html", null ],
    [ "rx_reg_t", "unionrx__reg__t.html", null ],
    [ "RXF0", "structRXF0.html", null ],
    [ "RXF1", "structRXF1.html", null ],
    [ "RXF2", "structRXF2.html", null ],
    [ "RXF3", "structRXF3.html", null ],
    [ "RXF4", "structRXF4.html", null ],
    [ "RXF5", "structRXF5.html", null ],
    [ "RXM0", "structRXM0.html", null ],
    [ "RXM1", "structRXM1.html", null ],
    [ "ST7789H2_Rgb888", "structST7789H2__Rgb888.html", null ],
    [ "Styles", "classStyles.html", [
      [ "LightStyles", "classLightStyles.html", null ]
    ] ],
    [ "StylesManager", "classStylesManager.html", null ],
    [ "TS_DrvTypeDef", "structTS__DrvTypeDef.html", null ],
    [ "TS_StateTypeDef", "structTS__StateTypeDef.html", null ],
    [ "TSENSOR_DrvTypeDef", "structTSENSOR__DrvTypeDef.html", null ],
    [ "TSENSOR_InitTypeDef", "structTSENSOR__InitTypeDef.html", null ],
    [ "uCAN_MSG", "unionuCAN__MSG.html", null ],
    [ "uint16_pair_t", "unionuint16__pair__t.html", null ],
    [ "View", "classView.html", [
      [ "Chart", "classChart.html", [
        [ "BarChart", "classBarChart.html", null ]
      ] ],
      [ "HomeView", "classHomeView.html", null ],
      [ "StatsView", "classStatsView.html", null ]
    ] ]
];